---
include:
  - project: 'cnap/gitlab-ci-templates'
    ref: main
    file: 'gitlab-ci/security.gitlab-ci.yml'

default:
  image:
    name: $IMAGE_CI_NODEJS20_DEBIAN
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  tags:
    - CnapGroupProduction

stages:
  - test
  - publish

build-push-image:
  stage: publish
  image:
    name: registry1.dso.mil/cnap/tool/kaniko:33cf33c-3852872
    entrypoint: [ "" ]
  variables:
    REGISTRY: registry1.dso.mil/cnap/trivy-glass
  before_script:
    - mkdir -p /kaniko/.docker
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
  script:
    # Set tag based on branch/tag condition
    - |
      case "$CI_COMMIT_REF_NAME" in
        "$CI_DEFAULT_BRANCH") tag="latest" ;;
        "$CI_COMMIT_TAG") tag="$CI_COMMIT_TAG" ;;
        *) tag="$CI_COMMIT_SHA" ;;
      esac

    # Build image and output tar
    - |
      /kaniko/executor \
      --context docker/ \
      --dockerfile Dockerfile \
      --destination $REGISTRY:$tag \
      --label "source=code.il4.dso.mil/cnap/dashboard" \
      --label "revision=$CI_COMMIT_SHORT_SHA" \
      --no-push \
      --tarPath="image.tar"

    # Switch credentials for pushing
    - echo $DOCKER_AUTH_CONFIG_CNAP_WRITE > /kaniko/.docker/config.json

    # Push image
    - crane push image.tar $REGISTRY:$tag

    # Conditionally tag the image as latest if not already latest
    - |
      if [ "$tag" != "latest" ]; then
        crane tag $REGISTRY:$tag latest
      fi

  rules:
    - if: '$CI_COMMIT_TAG != null || $CI_PIPELINE_SOURCE == "web"'
      when: always



# Prevent scanning pushes to Main as code has already been scanned on Merge Request
svelte-lint:
  stage: test
  script:
    - npm ci
    - npm run lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/

clamav_scan:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

kics-iac-sast :
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

secret_detection:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

semgrep-sast:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always
