{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "trivy-glass.namespace" . }}
data:
  config.json: |
    {{ .Values.configMap.data | nindent 4 }}
{{- end }}
