apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivy-glass.name" . }}
  namespace: {{ include "trivy-glass.namespace" . }}
spec:
  selector:
    app: {{ include "trivy-glass.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: 3000
